//
//  RatingControl.swift
//  FoodTracker
//
//  Created by Jack K on 2/10/17.
//  Copyright © 2017 Jack K. All rights reserved.
//


import UIKit

// IBDesignable lets the interface builder instanstiate and draw a copy of the control directly on the canvas
@IBDesignable class RatingControl: UIStackView {

    
    //MARK: Properties
    private var ratingButtons = [UIButton]()
    
    var rating = 0
    
    //MARK: Initialization (figure out the differences)
    override init(frame: CGRect) {
        super.init(frame: frame)
        setupButtons()
    }
    
    required init(coder: NSCoder) {
        super.init(coder: coder)
        setupButtons()
    }
    
    //MARK: Button Action
    func ratingButtonTapped(button: UIButton){
        print("button pressed")
    }
    
    //MARK: Private Methods
    private func setupButtons(){
        
        // 5 buttons
        for _ in 0..<5 {
            // Create the button
            let button = UIButton()
            button.backgroundColor = UIColor.red
            
            // Add constraints
            button.translatesAutoresizingMaskIntoConstraints = false // turn off autogenerated constraints
            button.heightAnchor.constraint(equalToConstant: 44.0).isActive = true
            button.widthAnchor.constraint(equalToConstant: 44.0).isActive = true
            
            // Setup the button action
            // A selector is an opaque value that identifies the method
            button.addTarget(self, action: #selector(ratingButtonTapped(button:)), for: .touchUpInside)
            
            // Add the new button to the stack
            addArrangedSubview(button)
            
            // Add the new button to the rating button array
            ratingButtons.append(button)
        }
        
    }
}
